---
version: "3"
services:
    runner:
        image: matthijsbos/nerdrage-dev
    webapp:
        build: .
    selenium:
        image: selenium/standalone-chrome:3.141.59
        shm_size: 2g
        ports:
            - "4444:4444"        
    crossbar:
        image: crossbario/crossbar
        ports: 
            - "8080:8080"